### ISSUE TITLE
Requires Python >=3.7

### ISSUE THREAD

**Issue by andymlau** [greener-group/progres#1]
Hey Joe, 

Great work, just a quick note that PyTorch 1.12.0 requires at least python 3.7: 

```
pytorch==1.12.0 -> python[version='>=3.10,<3.11.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0|>=3.7,<3.8.0a0']
```

**Comment by jgreener64** [comment]
Thanks Andy, I just changed that in the readme. Let me know of any other issues you run into or usability suggestions you have.

Hoping to put up an updated pre-print within a couple of months too.
